name: Tests

on:
  workflow_dispatch:
  push:
      branches:
          - main
  pull_request:
      branches:
          - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [
          8.4,
          8.3,
          8.2,
          8.1,
          8.0,
        ]

    name: PHP v${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP v${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php }}
            tools: composer:v2

      - name: Validate Composer
        run: composer validate --strict

      - name: Install PHP Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit
